package com.smartjob.user.mapper;

import com.smartjob.user.dto.Phone;
import com.smartjob.user.dto.PostUserRequest;
import com.smartjob.user.dto.PostUserResponse;
import com.smartjob.user.entity.PhoneEntity;
import com.smartjob.user.entity.UserEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * Mapper for converting between DTOs (generated by OpenAPI) and JPA entities.
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Converts a PostUserRequest DTO into a UserEntity.
     *
     * @param request the request DTO
     * @return a user entity (without encrypted password, token, or ID)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "token", ignore = true)
    @Mapping(target = "created", ignore = true)
    @Mapping(target = "modified", ignore = true)
    @Mapping(target = "lastLogin", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    @Mapping(target = "phones", source = "phones", qualifiedByName = "phoneDtoListToEntityList")
    UserEntity toEntity(PostUserRequest request);

    /**
     * Converts a list of Phone DTOs into a list of PhoneEntity objects.
     * Properly maps field names that differ between the DTO and the entity.
     *
     * @param phones the list of phone DTOs
     * @return the list of phone entities
     */
    @Named("phoneDtoListToEntityList")
    List<PhoneEntity> phoneDtoListToEntityList(List<Phone> phones);

    /**
     * Converts a Phone DTO into a PhoneEntity.
     *
     * @param phone the phone DTO
     * @return the phone entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "user", ignore = true)
    PhoneEntity phoneToEntity(Phone phone);

    /**
     * Converts a UserEntity into a PostUserResponse DTO.
     * Maps all fields required for the response.
     *
     * @param user the user entity
     * @return the response DTO
     */
    @Mapping(target = "created", source = "created", qualifiedByName = "toOffsetDateTime")
    @Mapping(target = "modified", source = "modified", qualifiedByName = "toOffsetDateTime")
    @Mapping(target = "lastLogin", source = "lastLogin", qualifiedByName = "toOffsetDateTime")
    @Mapping(target = "isActive", source = "isActive")
    @Mapping(target = "phones", source = "phones", qualifiedByName = "phoneEntityListToDtoList")
    PostUserResponse toResponse(UserEntity user);

    /**
     * Converts a list of PhoneEntity objects into a list of Phone DTOs.
     *
     * @param phones the list of phone entities
     * @return the list of phone DTOs
     */
    @Named("phoneEntityListToDtoList")
    List<Phone> phoneEntityListToDtoList(List<PhoneEntity> phones);

    /**
     * Converts a PhoneEntity into a Phone DTO.
     *
     * @param phone the phone entity
     * @return the phone DTO
     */
    Phone phoneToDto(PhoneEntity phone);

    @Named("toOffsetDateTime")
    default OffsetDateTime toOffsetDateTime(LocalDateTime localDateTime) {
        return localDateTime != null ? localDateTime.atOffset(ZoneOffset.UTC) : null;
    }
}