package com.smartjob.user.exception.handler;

import com.smartjob.user.dto.Error;
import com.smartjob.user.exception.EmailAlreadyExistsException;
import com.smartjob.user.exception.InvalidEmailFormatException;
import com.smartjob.user.exception.InvalidPasswordFormatException;
import com.smartjob.user.mapper.ErrorMapper;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.ConstraintViolationException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.bind.support.WebExchangeBindException;
import reactor.core.publisher.Mono;

import java.util.stream.Collectors;

/**
 * Global exception handler for the application.
 * Captures all exceptions and converts them into JSON responses using
 * the Error class generated by OpenAPI: {"message": "error message"}
 *
 * Returns the appropriate HTTP status codes based on the error type.
 */
@Slf4j
@RestControllerAdvice
@RequiredArgsConstructor
public class GlobalExceptionHandler {

    private final ErrorMapper errorMapper;

    /**
     * Handles exceptions for already registered emails.
     * HTTP 409 Conflict
     */
    @ExceptionHandler(EmailAlreadyExistsException.class)
    public Mono<ResponseEntity<Error>> handleEmailAlreadyExists(EmailAlreadyExistsException ex) {
        log.warn("Email ya existe: {}", ex.getMessage());
        Error error = errorMapper.toError(ex);
        return Mono.just(ResponseEntity.status(HttpStatus.CONFLICT).body(error));
    }

    /**
     * Handles exceptions for invalid email format.
     * HTTP 400 Bad Request
     */
    @ExceptionHandler(InvalidEmailFormatException.class)
    public Mono<ResponseEntity<Error>> handleInvalidEmailFormat(InvalidEmailFormatException ex) {
        log.warn("Formato de email inválido: {}", ex.getMessage());
        Error error = errorMapper.toError(ex);
        return Mono.just(ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error));
    }

    /**
     * Handles exceptions for invalid password format.
     * HTTP 400 Bad Request
     */
    @ExceptionHandler(InvalidPasswordFormatException.class)
    public Mono<ResponseEntity<Error>> handleInvalidPasswordFormat(InvalidPasswordFormatException ex) {
        log.warn("Formato de password inválido: {}", ex.getMessage());
        Error error = errorMapper.toError(ex);
        return Mono.just(ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error));
    }

    /**
     * Handles Bean Validation (Jakarta Validation) errors.
     * These are errors generated by annotations such as @Valid, @Pattern, @Size,
     * etc., in the DTOs generated by OpenAPI.
     * HTTP 400 Bad Request
     */
    @ExceptionHandler(WebExchangeBindException.class)
    public Mono<ResponseEntity<Error>> handleValidationErrors(WebExchangeBindException ex) {
        log.warn("Error de validación en DTO: {}", ex.getMessage());

        String errorMessage = ex.getBindingResult()
                .getFieldErrors()
                .stream()
                .map(error -> {
                    String field = error.getField();
                    String message = error.getDefaultMessage();
                    return field + ": " + message;
                })
                .collect(Collectors.joining("; "));

        if (errorMessage.isEmpty()) {
            errorMessage = "Error de validación en los datos enviados";
        }

        Error error = errorMapper.toError(errorMessage);
        return Mono.just(ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error));
    }

    /**
     * Handles ConstraintViolationException (programmatic Jakarta Validation
     * validations).
     * HTTP 400 Bad Request
     */
    @ExceptionHandler(ConstraintViolationException.class)
    public Mono<ResponseEntity<Error>> handleConstraintViolation(ConstraintViolationException ex) {
        log.warn("Violación de constraint: {}", ex.getMessage());

        String errorMessage = ex.getConstraintViolations()
                .stream()
                .map(ConstraintViolation::getMessage)
                .collect(Collectors.joining("; "));

        Error error = errorMapper.toError(errorMessage);
        return Mono.just(ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error));
    }

    /**
     * Handles IllegalArgumentException (business logic validations).
     * HTTP 400 Bad Request
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public Mono<ResponseEntity<Error>> handleIllegalArgument(IllegalArgumentException ex) {
        log.warn("Argumento inválido: {}", ex.getMessage());
        Error error = errorMapper.toError(ex);
        return Mono.just(ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error));
    }

    /**
     * Maneja RuntimeException genéricas.
     * HTTP 500 Internal Server Error
     */
    @ExceptionHandler(Exception.class)
    public Mono<ResponseEntity<Error>> handleGenericException(Exception ex) {
        log.error("Error interno del servidor", ex);
        Error error = errorMapper.toError("Error interno del servidor");
        return Mono.just(ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(error));
    }

    /**
     * Handles generic RuntimeException errors.
     * HTTP 500 Internal Server Error
     */
    @ExceptionHandler(RuntimeException.class)
    public Mono<ResponseEntity<Error>> handleRuntimeException(RuntimeException ex) {
        log.error("Error de ejecución: {}", ex.getMessage(), ex);

        if (ex instanceof EmailAlreadyExistsException ||
                ex instanceof InvalidEmailFormatException ||
                ex instanceof InvalidPasswordFormatException ||
                ex instanceof IllegalArgumentException) {
            throw ex;
        }

        Error error = errorMapper.toError("Error procesando la solicitud");
        return Mono.just(ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(error));
    }
}
