package com.smartjob.user.controller;

import com.smartjob.user.dto.PostUserRequest;
import com.smartjob.user.dto.PostUserResponse;
import com.smartjob.user.service.domain.UserService;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

/**
 * REST controller for user operations.
 * Implements the UsersApi interface generated by OpenAPI.
 */
@Slf4j
@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1")
public class UserController implements UsersApi {

    private final UserService userService;

    /**
     * POST /users endpoint - Create a new user
     *
     * Implements the operation defined in OpenAPI.
     *
     * @param postUserRequest DTO containing the user data to create
     * @param exchange        web request context
     * @return Mono with ResponseEntity 201 and the created user
     */
    @Override
    public Mono<ResponseEntity<PostUserResponse>> postUser(
            @Valid Mono<PostUserRequest> postUserRequest,
            ServerWebExchange exchange) {
        log.debug("Recibida petición POST /users");
        return postUserRequest
                .doOnNext(request -> log.info("Creando usuario con email: {}", request.getEmail()))
                .flatMap(userService::createUser)
                .map(response -> {
                    log.info("Usuario creado exitosamente con ID: {}", response.getId());
                    return ResponseEntity
                            .status(HttpStatus.CREATED)
                            .body(response);
                })
                .doOnError(error -> log.error("Error al crear usuario: {}", error.getMessage()));
    }
}